### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by meteguerlek** [vyuldashev/laravel-queue-rabbitmq#390] opened 2020-12-22 23:28 UTC

**Comment by JulianMar** [comment] 2021-01-08 11:08
currently not possible due to the delay in the client library https://github.com/php-amqplib/php-amqplib/pull/858

**Comment by stadeleon** [comment] 2021-02-25 23:16
https://github.com/php-amqplib/php-amqplib/pull/858 
It is merged!

**Comment by Demozo** [comment] 2021-03-10 13:34
[phpamqplib/php-amqplib](https://github.com/php-amqplib/php-amqplib/) released a v3.0.0 RC build that has support for PHP 8. This however introduces issues with this library with regards to it requiring a `2.12.x` version of amqplib. Aliasing this to the v3 RC build like I have done as demonstrated in #413 throws a "rest" option exception. Using the `php artisan queue:work` command as opposed to `php artisan rabbitmq:consume` circumvents this and does not cause the aforementioned exception to be thrown.

Best to either implement amqplib directly if you need PHP8 and amqp now and wish to use `php artisan rabbitmq:consume`, or wait for this package to be updated if PHP8 isn't urgent for you.

In addition; it may also cause #396 exception to be thrown, however I am still researching which situation exactly causes this. I have had no luck reproducing this on another system/environment, so if anyone could test this hypothesis on their side that would be appreciated.

**Comment by M-Porter** [comment] 2023-01-25 19:03
PHP 8 support should be good now.

**Closed by M-Porter** 2023-01-25 19:03 UTC
