### ISSUE TITLE
Work not customer

### ISSUE THREAD

**Issue by chuxiangqaz** [vyuldashev/laravel-queue-rabbitmq#333] opened 2020-04-24 18:48 UTC
- Laravel Version: Lumen 5.8
- Package Version: 7.2
- RabbitMQ Version:3.77

**process not consume**
Use supervisor to manage the process `php / usr / share / nginx / html / src / artisan queue: work --quiet --sleep = 5 --tries = 1 --timeout = 10`, but the process does not consume messages。

![image](https://user-images.githubusercontent.com/20558417/80245995-48a5c680-869e-11ea-99cb-08b4ce5fc6d3.png)

**Steps To Reproduce**
1. Use supervisor to manage the process `php / usr / share / nginx / html / src / artisan queue: work --quiet --sleep = 5 --tries = 1 --timeout = 10`

2. **wait 10 min**

3. push message to queue

**Expected behavior**
1. process console ` [2020-04-25 02:20:10][5ea32dd697c249.19596175] Processing:ProductSynMqListener `， always waiting

2. not find log 

**Additional context**

config 
```
sleep_on_error => false
```

**Comment by vyuldashev** [comment] 2020-04-24 18:49
Package version 7.2 is not supported already.

**Comment by chuxiangqaz** [comment] 2020-04-24 18:52
I  upgrade `V10` ，Can solve this problem code?

**Comment by vyuldashev** [comment] 2020-04-24 19:09
Yes. Try v10.2.0

**Comment by chuxiangqaz** [comment] 2020-04-24 19:17
i use `v10.1.3` , Can solve this problem code?

**Comment by vyuldashev** [comment] 2020-04-24 19:20
I just released v10.2.0, should be fixed.

**Comment by chuxiangqaz** [comment] 2020-04-25 11:18
- Laravel Version: lumen 6.*
- Package Version: `v10.2.0`
- RabbitMQ Version:3.77
- command `php /usr/share/nginx/html/src/artisan queue:work --sleep=5 --tries=1`

The process will still be suspended，but the process is not working anymore 。
**supervisor console running**，
command console：
```
[2020-04-25 18:47:51][rPKgJpiliMpA0RmVBOubxS18nyhpoVfg] Processing: App\Jobs\UpdateGoodsJob
[2020-04-25 18:47:51][rPKgJpiliMpA0RmVBOubxS18nyhpoVfg] Processed:  App\Jobs\UpdateGoodsJob
[2020-04-25 19:06:46][LwsUxEuI0hEjYy6zrC0JrRZpf9tITEEA] Processing: App\Jobs\UpdateGoodsJob

```

**Comment by adm-bome** [comment] 2020-04-25 19:51
As im not mistaking: 
```sh
artisan queue:work 
```
Starts a long running proces with sub processes
Supervisor is useless in this case because the main process is running and never dies. 

Maybe use 'queue:listen' and specify your queue

**Comment by chuxiangqaz** [comment] 2020-04-26 05:16
The problem now is: work is running, after waiting for more than 10 minutes, I receive a message that does not show Processend, the process is not processed rabbitmq new message.
```
$ php / usr / share / nginx / html / src / artisan queue: work --sleep = 5 --tries = 1

[2020-04-25 18:47:51] [rPKgJpiliMpA0RmVBOubxS18nyhpoVfg] Processing: App \ Jobs \ UpdateGoodsJob
[2020-04-25 18:47:51] [rPKgJpiliMpA0RmVBOubxS18nyhpoVfg] Processed: App \ Jobs \ UpdateGoodsJob
[2020-04-25 19:06:46] [LwsUxEuI0hEjYy6zrC0JrRZpf9tITEEA] Processing: App \ Jobs \ UpdateGoodsJob
```

**Comment by adm-bome** [comment] 2020-04-26 09:19
Will look into it. 
The worker(s) is/are responsible for the status output: `Proccessing`, `Proccessed`,  `Failed`.

Is the message retried or put back into the queue? Is the message acknowledged or rejected?
Is the message unacked?
Is the message gone?

What happens when you try to dispatch a seccond/third Job after the 10 min?

**Comment by chuxiangqaz** [comment] 2020-04-26 09:23
Q：Is the message retried or put back into the queue?

**Comment by adm-bome** [comment] 2020-04-26 13:18
**Laravel Version: 7.8.1
Package Version: v10.2.0
RabbitMQ Version: 3.8.2**

Can't reproduce the issue with these versions.

- Clean install Laravel
- Installed this library
- Configure Laravel to use rabbitmq connection
- Create TestJob
- Dispatch TestJob (multiple times)

```sh
$ php artisan queue:work --sleep=5 --tries=1
[2020-04-26 11:12:59][wAwbpsvhztLIzfMkfKqq0oPQq8O5emSm] Processing: App\Jobs\TestJob
[2020-04-26 11:12:59][wAwbpsvhztLIzfMkfKqq0oPQq8O5emSm] Processed:  App\Jobs\TestJob

[2020-04-26 11:13:29][ItlcLaRAC5SJw4G4HJeNKT7xlYuKT8BJ] Processing: App\Jobs\TestJob
[2020-04-26 11:13:29][ItlcLaRAC5SJw4G4HJeNKT7xlYuKT8BJ] Processed:  App\Jobs\TestJob

[2020-04-26 11:26:24][ZAoB0MINlchW1aey6KwRYEqbXm23diTB] Processing: App\Jobs\TestJob
[2020-04-26 11:26:24][ZAoB0MINlchW1aey6KwRYEqbXm23diTB] Processed:  App\Jobs\TestJob

[2020-04-26 11:26:34][41az1jzUgF8W589LBas5MLnsyyGW3CWR] Processing: App\Jobs\TestJob
[2020-04-26 11:26:34][41az1jzUgF8W589LBas5MLnsyyGW3CWR] Processed:  App\Jobs\TestJob
```


**Lumen Version: 7.1.0
Package Version: v10.2.0
RabbitMQ Version: 3.8.2**

Can't reproduce the issue with these versions.

- Clean install Lumen
- Installed this library
- Configure Lumen to use rabbitmq connection
- Use ExampleJob
- Dispatch ExampleJob (multiple times)

```sh
$ php artisan queue:work --sleep=5 --tries=1
[2020-04-26 12:32:23][zocQR7RK370VVOJxC6MV9ks2ScYmoqiy] Processing: App\Jobs\ExampleJob
[2020-04-26 12:32:23][zocQR7RK370VVOJxC6MV9ks2ScYmoqiy] Processed:  App\Jobs\ExampleJob

[2020-04-26 12:32:28][75ka7IrE3EwED1r5iWjDDjMePDfPDmsJ] Processing: App\Jobs\ExampleJob
[2020-04-26 12:32:28][75ka7IrE3EwED1r5iWjDDjMePDfPDmsJ] Processed:  App\Jobs\ExampleJob

[2020-04-26 12:43:34][nWikYXcmZTi6SM45ftyoMknIHCpHpFVy] Processing: App\Jobs\ExampleJob
[2020-04-26 12:43:34][nWikYXcmZTi6SM45ftyoMknIHCpHpFVy] Processed:  App\Jobs\ExampleJob

[2020-04-26 12:44:43][3MxcGJWaKaM7c6BMmTZKxwl9Knxu9TUO] Processing: App\Jobs\ExampleJob
[2020-04-26 12:44:43][3MxcGJWaKaM7c6BMmTZKxwl9Knxu9TUO] Processed:  App\Jobs\ExampleJob
```



**Lumen Version: 6.3.3
Package Version: v10.2.0
RabbitMQ Version: 3.7.25**

Can't reproduce the issue with these versions.

- Clean install Lumen
- Installed this library
- Configure Lumen to use rabbitmq connection
- Use ExampleJob
- Dispatch ExampleJob (multiple times)

```sh
$ php artisan queue:work --sleep=5 --tries=1
[2020-04-26 13:06:30][lU8SZokxo9pQ1SzcG9PIKh42NP8a740J] Processing: App\Jobs\ExampleJob
[2020-04-26 13:06:30][lU8SZokxo9pQ1SzcG9PIKh42NP8a740J] Processed:  App\Jobs\ExampleJob

[2020-04-26 13:06:40][jlYEqzjFs3zphtCqGHPmZYD915732quH] Processing: App\Jobs\ExampleJob
[2020-04-26 13:06:40][jlYEqzjFs3zphtCqGHPmZYD915732quH] Processed:  App\Jobs\ExampleJob

[2020-04-26 13:17:20][bGr8Odi6niPH2jROTWPCKfUJ7pl4Xadu] Processing: App\Jobs\ExampleJob
[2020-04-26 13:17:20][bGr8Odi6niPH2jROTWPCKfUJ7pl4Xadu] Processed:  App\Jobs\ExampleJob

[2020-04-26 13:17:32][z7UGfgXfXna7p0NDdBdicVusuSmyWJBL] Processing: App\Jobs\ExampleJob
[2020-04-26 13:17:32][z7UGfgXfXna7p0NDdBdicVusuSmyWJBL] Processed:  App\Jobs\ExampleJob
```

**Comment by adm-bome** [comment] 2020-05-03 17:18
@vyuldashev @chuxiangqaz  I think this issue can be closed.

**Closed** 2020-05-28 17:42 UTC
